saveExact: true
allowBuilds:
  unrs-resolver@1.12.2: true
overrides:
  brace-expansion@<2: 1.1.18
  brace-expansion@>=4 <6: 5.0.9
  baseline-browser-mapping@>=2 <3: 2.11.0
  browserslist@<=4.28.6: 4.28.7
  js-yaml@>=4 <5: 4.3.2
